builders:
  firestorm_builder:
    import: "package:firestorm/gen/builder.dart"
    builder_factories: ["firestormBuilder"]
    build_extensions:
      "$lib$": ["generated/firestorm_models.dart"]
    auto_apply: dependents
    build_to: source