builders:
  firestorm_builder:
    import: "package:firestorm/gen/firestorm_builder.dart"
    builder_factories: ["firestormBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source